page_frag: split types in page_frag_cache.h into page_frag_types.h
It seems virt_to_page() can not be used in the below file:
arch/x86/kernel/asm-offsets.c
Not even in the .h file included by it, using virt_to_page()
causes below error:
  CC      arch/x86/kernel/asm-offsets.s
In file included from ./arch/x86/include/asm/page.h:89,
                 from ./arch/x86/include/asm/thread_info.h:12,
                 from ./include/linux/thread_info.h:60,
                 from ./include/linux/spinlock.h:60,
                 from ./include/linux/swait.h:7,
                 from ./include/linux/completion.h:12,
                 from ./include/linux/crypto.h:15,
                 from arch/x86/kernel/asm-offsets.c:9:
./include/asm-generic/memory_model.h:37:34: error:
error: ‘vmemmap’ undeclared (first use in this function);

As next patch is about to replace 'struct page_frag' with
'struct page_frag_cache' in linux/sched.h, which is included
by the asm-offsets.s above, in order to avoid including a .h
file in using the virt_to_page() for asm-offsets.s, spilt the
struct and function types in page_frag_cache.h using the
virt_to_page() into page_frag_types.h, so that
page_frag_types.h can be included in linux/sched.h.

Signed-off-by: Yunsheng Lin <linyunsheng@huawei.com>